# AutoViral Docker Compose Configuration
# All ports and credentials come from .env file

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: autoviral-api
    ports:
      - "${API_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3000
      - AUTH_BEARER_KEY=${AUTH_BEARER_KEY}
      - LLM_PROVIDER=${LLM_PROVIDER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - BROWSER_USE_API_KEY=${BROWSER_USE_API_KEY}
      - PEXELS_API_KEY=${PEXELS_API_KEY}
      - DAYTONA_API_KEY=${DAYTONA_API_KEY}
      - DAYTONA_API_URL=${DAYTONA_API_URL}
      - INSTAGRAM_USERNAME=${INSTAGRAM_USERNAME}
      - INSTAGRAM_PASSWORD=${INSTAGRAM_PASSWORD}
    volumes:
      - ./data:/app/data
      - ./media:/app/media
    restart: unless-stopped
    networks:
      - autoviral-network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: autoviral-worker
    ports:
      - "${WORKER_PORT:-7000}:3001"
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL}
      - AUTH_BEARER_KEY=${AUTH_BEARER_KEY}
      - DISCOVERY_INTERVAL_MINUTES=${DISCOVERY_INTERVAL_MINUTES}
      - LLM_PROVIDER=${LLM_PROVIDER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - BROWSER_USE_API_KEY=${BROWSER_USE_API_KEY}
      - PEXELS_API_KEY=${PEXELS_API_KEY}
      - DAYTONA_API_KEY=${DAYTONA_API_KEY}
      - DAYTONA_API_URL=${DAYTONA_API_URL}
      - INSTAGRAM_USERNAME=${INSTAGRAM_USERNAME}
      - INSTAGRAM_PASSWORD=${INSTAGRAM_PASSWORD}
    volumes:
      - ./data:/app/data
      - ./media:/app/media
    restart: unless-stopped
    networks:
      - autoviral-network

networks:
  autoviral-network:
    driver: bridge
